dblessConfig:
  config:
    _format_version: "1.1"
    services:
      - name: stock-prediction
        url: http://stock-prediction:8000
        routes:
        - name: stock-prediction
          paths:
          - /stock-prediction
